language: c
compiler: gcc

services:
  - docker

matrix:
  include:
    - env:
      - ARCH=x86_64
      - DOCKER_IMAGE=quay.io/appimage/appimagebuild
    - env:
      - ARCH=i686
      - DOCKER_IMAGE=quay.io/appimage/appimagebuild-i386
    - env:
      - ARCH=x86_64
      addons:
        apt:
          update: true
          packages:
          - libfuse-dev
          - desktop-file-utils

script:
  - if [ "$TRAVIS_EVENT_TYPE" == "cron" ] && [ "$ARCH" == "x86_64" ] ; then bash travis/tag-using-cron.sh ; else bash travis/travis-build.sh ; fi 

notifications:
  irc:
    channels:
    - "chat.freenode.net#AppImage"
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: always    # options: [always|never|change] default: always
    template:
    - "%{repository} build %{build_number}: %{result} %{build_url}"
    use_notice: true
    # skip_join: true
